/**
 * Project references – locale-aware (de/en/es/fr/it/pt). Language-neutral
 * fields (year, location, category) live in `base`; translated fields (title,
 * description, technologies) live in `txt` and are merged per locale.
 *
 * Do not fabricate clients or projects.
 */
import { pageLocale, type Locale } from "@/i18n/config";

export type ProjectCategory =
  | "infrastruktur"
  | "logistik"
  | "abwasser"
  | "stahl"
  | "retrofit"
  | "kies"
  | "kommunikation";

export type Project = {
  year: string;
  title: string;
  location: string;
  category: ProjectCategory;
  technologies: string[];
  description: string;
};

type Base = { year: string; location: string; category: ProjectCategory };
type Txt = { title: string; description: string; technologies: string[] };

const base: Base[] = [
  { year: "2024–2026", location: "Kanton Zürich", category: "infrastruktur" },
  { year: "2019–2021", location: "Zürich Mülligen", category: "logistik" },
  { year: "2016–2018", location: "Basel", category: "logistik" },
  { year: "2013–2016", location: "Zermatt VS", category: "abwasser" },
  { year: "2026", location: "Zürich Altstetten", category: "retrofit" },
  { year: "2025–2026", location: "Schweiz", category: "infrastruktur" },
  { year: "2023", location: "Schweiz", category: "infrastruktur" },
  { year: "2023", location: "Schweiz", category: "infrastruktur" },
  { year: "2018", location: "ARA Reinach ZH", category: "abwasser" },
  { year: "2018", location: "ARA Elgg ZH", category: "abwasser" },
  { year: "2017", location: "Sennhof ZH", category: "abwasser" },
  { year: "2017", location: "Huggenberg ZH", category: "abwasser" },
  { year: "2017", location: "Dickbuch ZH", category: "abwasser" },
  { year: "2017", location: "Hauptwil SG", category: "abwasser" },
  { year: "2017", location: "Niederwil SG", category: "abwasser" },
  { year: "2016", location: "ARA Lugano TI", category: "abwasser" },
  { year: "2016", location: "ARA Zermatt VS", category: "abwasser" },
  { year: "2015", location: "ARA Zermatt VS", category: "abwasser" },
  { year: "2015", location: "ARA Oensingen SO", category: "abwasser" },
  { year: "2015", location: "Arnegg SG", category: "abwasser" },
  { year: "2015", location: "Andwil SG", category: "abwasser" },
  { year: "2015", location: "ARA Zermatt VS", category: "abwasser" },
  { year: "2015", location: "Henessen SG", category: "abwasser" },
  { year: "2015", location: "Rheinfelden AG", category: "abwasser" },
  { year: "2014", location: "ARA Zermatt VS", category: "abwasser" },
  { year: "2015", location: "Werdhölzli, Zürich", category: "abwasser" },
  { year: "2014", location: "Werdhölzli, Zürich", category: "abwasser" },
  { year: "2013", location: "ARA Buchs ZH", category: "abwasser" },
  { year: "2005–2011", location: "Mexiko", category: "stahl" },
  { year: "2005–2011", location: "Türkei", category: "stahl" },
  { year: "2005–2011", location: "Lettland", category: "stahl" },
  { year: "2005–2011", location: "Weissrussland", category: "stahl" },
  { year: "2014", location: "Horth, Deutschland", category: "stahl" },
  { year: "2005–2011", location: "Brasilien", category: "retrofit" },
  { year: "2005–2011", location: "Deutschland", category: "retrofit" },
  { year: "2014", location: "Kehl, Deutschland", category: "retrofit" },
  { year: "2014", location: "Warren, USA", category: "retrofit" },
  { year: "2025", location: "Birr AG", category: "kies" },
  { year: "2025–2026", location: "Schafisheim AG", category: "kies" },
  { year: "2025", location: "Schweiz", category: "retrofit" },
  { year: "2026", location: "Schweiz", category: "infrastruktur" },
  { year: "2025", location: "ARA Rorbas ZH", category: "kommunikation" },
  { year: "2024", location: "ARA Lenzerheide GR", category: "abwasser" },
  { year: "2024", location: "Dietikon ZH", category: "infrastruktur" },
  { year: "2026", location: "ARA Lucens VD", category: "abwasser" },
];

const txt: Record<Locale, Txt[]> = {
  de: [
    { title: "EKZ – Öffentliche Beleuchtung, Kanton Zürich", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Zentrale, sichere Lichtsteuerung für die Elektrizitätswerke des Kantons Zürich (EKZ): rund 3'000 SPS (SIMATIC S7-1500) in über 2'500 Trafostationen, gesteuert mit WinCC OA SCADA und programmiert im TIA Portal. Verschlüsselte OPC-UA-Kommunikation inkl. OPC UA GDS Push für die zentrale Zertifikatsverwaltung. Realisiert mit Siemens Schweiz DI AG." },
    { title: "Mix-Mail Verteilzentrum – Schweizerische Post", technologies: ["Siemens", "Cross-Belt-Sorter", "Fördertechnik", "Automatisierung"], description: "Software-Entwicklung für die vollautomatische Sortierung von Mischsendungen (Mix-Mail) – eine Weltneuheit in der Sortierung. Anlagenleistung bis 19'000 Sendungen/Stunde, ca. 1'400 Zielstellen und 5 Cross-Belt-Sorter auf zwei Ebenen. Realisiert mit Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Basel – neues Logistikzentrum", technologies: ["Siemens", "Fördertechnik", "Automatisierung"], description: "Software-Entwicklung für ein komplettes Logistikzentrum von DHL Express – Konzepte für Steuerung, Automatisierung sowie anlagen- und applikationsspezifische Software. Verantwortlich für die Fördertechnik mit über 500 Bändern, Sortern und Endstellen; Sortierleistung rund 10'000 Sendungen/Stunde. Realisiert mit Siemens Logistics AG." },
    { title: "ARA Zermatt – grösste Membranbiologieanlage der Schweiz", technologies: ["Siemens S7", "WinCC OA", "HLK", "SCADA"], description: "Neuprogrammierung der gesamten Kläranlage samt HLK – die grösste Membranbiologieanlage der Schweiz, in einer Kaverne im Berginnern. Steuerung mit über 10 SIMATIC-CPUs (STEP 7) und WinCC OA als SCADA-Leitsystem; Ausbaugrösse 60'000 Einwohner." },
    { title: "SBB – Querwagen 360°, Zürich Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Hochrüstung der bestehenden SPS von STEP 7 auf TIA Portal samt Software-Anpassung für die Querwagen-Verschiebung mit 360-Grad-Funktion. Realisiert mit Siemens Schweiz DI AG." },
    { title: "Equinix – Rechenzentrum-Erweiterung", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Erweiterung eines bestehenden Rechenzentrums um ein neues Stockwerk samt Generatoren-System; Datenverarbeitung via Modbus RTU und TCP. Realisiert mit Siemens Schweiz DI AG." },
    { title: "Equinix – PCS 7 Upgrade auf V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Hochrüstung eines bestehenden Rechenzentrum-Projekts auf SIMATIC PCS 7 V9.1 (inkl. PH und IF). Realisiert mit Siemens Schweiz DI AG." },
    { title: "Equinix – PCS 7 Upgrade auf V9.1 (2. Standort)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Hochrüstung eines weiteren bestehenden Rechenzentrum-Projekts auf SIMATIC PCS 7 V9.1 (inkl. PH und IF). Realisiert mit Siemens Schweiz DI AG." },
    { title: "Regenbecken-Steuerung ARA Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für diverse Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Abwasserwärme-Nutzungsanlage ARA Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Erweiterung der Steuerung der Abwasserwärme-Nutzungsanlage (S7/WinCC OA)." },
    { title: "Regenbecken-Steuerung Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Abwasserwärme-Nutzungsanlage ARA Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programmierung der Steuerung der Abwasserwärme-Nutzungsanlage (S7/WinCC OA)." },
    { title: "Abwasserwärme-Nutzungsanlage ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmierung der Steuerung der Abwasserwärme-Nutzungsanlage (S7/WinCC OA)." },
    { title: "Abwasserwärme-Nutzungsanlage ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmierung der Steuerung der Abwasserwärme-Nutzungsanlage (S7/WinCC OA)." },
    { title: "Abwasserwärme-Nutzungsanlage ARA Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programmierung der Steuerung der Abwasserwärme-Nutzungsanlage (S7/WinCC OA)." },
    { title: "Regenbecken-Steuerung Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (TIA Portal/WinCC OA)." },
    { title: "Regenbecken-Steuerung ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmierung der Steuerung für ein Regenbecken (S7/WinCC OA)." },
    { title: "Wasserwerk-Station Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Steuerungsprogrammierung einer Wasserwerk-Station (TIA Portal/WinCC OA)." },
    { title: "Abwasserreinigungsanlage Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Steuerungsprogrammierung der Abwasserreinigungsanlage (S7/WinCC OA)." },
    { title: "Lüftungs- & Heizungssystem ARA Zermatt", technologies: ["Siemens S7", "HLK"], description: "Programmierung des Lüftungs- und Heizungssystems der Kläranlage Zermatt." },
    { title: "Sicherheitssteuerung Schlammverbrennung", technologies: ["S7-400 H", "Safety"], description: "Programmierung der fehlersicheren Sicherheitssteuerung auf S7-400 H-System für die Schlammverbrennungsanlage Werdhölzli." },
    { title: "Sicherheitssteuerung Schlammverbrennung", technologies: ["S7-400 H", "Safety"], description: "Programmierung der fehlersicheren Sicherheitssteuerung auf S7-400 H-System für die Schlammverbrennungsanlage Werdhölzli." },
    { title: "Steuerungsprogrammierung ARA Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Steuerungsprogrammierung der Kläranlage ARA Buchs ZH (S7/WinCC OA)." },
    { title: "Gitteranlage MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Schweisstechnik"], description: "Software-Entwicklung und Inbetriebsetzung der Gitteranlage MG630." },
    { title: "Radiatorenstrasse – Celikpan", technologies: ["Siemens S7", "Schweisstechnik"], description: "Software-Entwicklung und Inbetriebsetzung der Radiatorenstrasse." },
    { title: "Radiatorenstrasse – TIPRO Baltic", technologies: ["Siemens S7", "Schweisstechnik"], description: "Software-Entwicklung und Inbetriebsetzung der Radiatorenstrasse." },
    { title: "Radiatorenstrasse – Lida-Baltia", technologies: ["Siemens S7", "Schweisstechnik"], description: "Software-Entwicklung und Inbetriebsetzung der Radiatorenstrasse." },
    { title: "Schweissansteuerung Superflex (Jäger)", technologies: ["Siemens", "TCW Schweissprozessor"], description: "Schweissansteuerung an einer Superflex (Jäger) auf Siemens und TCW Schweissprozessor." },
    { title: "Gitteranlage Gerdau – Umbau S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Umbau der Gitteranlage von S5- auf S7-Steuerung." },
    { title: "Gitteranlage MG320 BDW – Umbau S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Umbau der Gitteranlage MG320 von S5- auf S7-Steuerung." },
    { title: "Umbau MG320 S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Umbau einer MG320 von S5- auf S7-Steuerung." },
    { title: "Software-Erweiterung Kaltziehanlage", technologies: ["Siemens S7"], description: "Software-Erweiterung einer Kaltziehanlage." },
    { title: "Kieswerk Birr – Visualisierung WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualisierung"], description: "Neue Anlagenvisualisierung für das Kieswerk Birr, umgesetzt auf WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – Visualisierung WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualisierung"], description: "Anlagenvisualisierung für das Kieswerk der KIBAG Kies Schafisheim AG, umgesetzt auf WinCC Unified PC Runtime." },
    { title: "WinCC Unified Modernisierung – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migration"], description: "Modernisierung einer bestehenden Visualisierung durch Migration von WinCC Advanced auf WinCC Unified." },
    { title: "KIBAG Waschplatz – Fahrzeugwaschanlage", technologies: ["WinCC Unified", "Comfort Panel", "Automatisierung"], description: "Steuerung und Visualisierung eines Fahrzeug-Waschplatzes der KIBAG auf einem WinCC Unified Comfort Panel." },
    { title: "ARA Rorbas – DALI-Beleuchtungssteuerung", technologies: ["DALI", "Beleuchtung", "Kommunikation"], description: "Umsetzung der Beleuchtungsansteuerung der ARA Rorbas ZH über den DALI-Bus. Realisiert im Auftrag von Rittmeyer." },
    { title: "ARA Lenzerheide – Biologie & Lüftung", technologies: ["Siemens S7", "WinCC OA", "HLK"], description: "Programmierung der Steuerung für Biologie und Lüftung der Kläranlage Lenzerheide." },
    { title: "EKZ Flusskraftwerk Dietikon – Reinigungsrechen", technologies: ["Siemens S7", "Automatisierung"], description: "Steuerung des Reinigungsrechens für das Flusskraftwerk Dietikon der EKZ." },
    { title: "ARA Lucens – Pumpstationen & Aussenbauwerke", technologies: ["Siemens S7", "WinCC OA"], description: "Software für vier Aussenbauwerke (Pumpstationen) der ARA Lucens sowie Visualisierung auf WinCC OA. Realisiert im Auftrag von Rittmeyer." },
  ],
  en: [
    { title: "EKZ – public lighting, Canton of Zurich", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Central, secure lighting control for the electricity utility of the Canton of Zurich (EKZ): around 3,000 PLCs (SIMATIC S7-1500) in more than 2,500 transformer stations, controlled with WinCC OA SCADA and programmed in TIA Portal. Encrypted OPC UA communication incl. OPC UA GDS Push for central certificate management. Realized with Siemens Schweiz DI AG." },
    { title: "Mix-Mail distribution centre – Swiss Post", technologies: ["Siemens", "Cross-belt sorter", "Conveyor tech", "Automation"], description: "Software development for the fully automated sorting of mixed mail (Mix-Mail) – a world first in sorting. Plant capacity up to 19,000 items per hour, approx. 1,400 chutes and 5 cross-belt sorters on two levels. Realized with Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Basel – new logistics centre", technologies: ["Siemens", "Conveyor tech", "Automation"], description: "Software development for a complete DHL Express logistics centre – concepts for control, automation and plant- and application-specific software. Responsible for the conveyor technology with more than 500 belts, sorters and chutes; sorting capacity around 10,000 items per hour. Realized with Siemens Logistics AG." },
    { title: "ARA Zermatt – largest membrane-biology plant in Switzerland", technologies: ["Siemens S7", "WinCC OA", "HVAC", "SCADA"], description: "Reprogramming of the entire wastewater plant including HVAC – the largest membrane-biology plant in Switzerland, in a cavern inside the mountain. Control with more than 10 SIMATIC CPUs (STEP 7) and WinCC OA as SCADA system; design size 60,000 population equivalents." },
    { title: "SBB – transfer car 360°, Zurich Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Upgrade of the existing PLC from STEP 7 to TIA Portal including software adaptation for the transfer-car shift with 360-degree function. Realized with Siemens Schweiz DI AG." },
    { title: "Equinix – data-centre extension", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Extension of an existing data centre by a new floor including a generator system; data processing via Modbus RTU and TCP. Realized with Siemens Schweiz DI AG." },
    { title: "Equinix – PCS 7 upgrade to V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Upgrade of an existing data-centre project to SIMATIC PCS 7 V9.1 (incl. PH and IF). Realized with Siemens Schweiz DI AG." },
    { title: "Equinix – PCS 7 upgrade to V9.1 (2nd site)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Upgrade of another existing data-centre project to SIMATIC PCS 7 V9.1 (incl. PH and IF). Realized with Siemens Schweiz DI AG." },
    { title: "Stormwater tank control – ARA Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for several stormwater tanks (TIA Portal/WinCC OA)." },
    { title: "Wastewater heat-recovery plant – ARA Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Extension of the control system for the wastewater heat-recovery plant (S7/WinCC OA)." },
    { title: "Stormwater tank control – Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Wastewater heat-recovery plant – ARA Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programming of the control system for the wastewater heat-recovery plant (S7/WinCC OA)." },
    { title: "Wastewater heat-recovery plant – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programming of the control system for the wastewater heat-recovery plant (S7/WinCC OA)." },
    { title: "Wastewater heat-recovery plant – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programming of the control system for the wastewater heat-recovery plant (S7/WinCC OA)." },
    { title: "Wastewater heat-recovery plant – ARA Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programming of the control system for the wastewater heat-recovery plant (S7/WinCC OA)." },
    { title: "Stormwater tank control – Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programming of the control system for a stormwater tank (TIA Portal/WinCC OA)." },
    { title: "Stormwater tank control – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programming of the control system for a stormwater tank (S7/WinCC OA)." },
    { title: "Water-works station Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Control programming of a water-works station (TIA Portal/WinCC OA)." },
    { title: "Wastewater treatment plant Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Control programming of the wastewater treatment plant (S7/WinCC OA)." },
    { title: "Ventilation & heating system – ARA Zermatt", technologies: ["Siemens S7", "HVAC"], description: "Programming of the ventilation and heating system of the Zermatt wastewater plant." },
    { title: "Safety controller – sludge incineration", technologies: ["S7-400 H", "Safety"], description: "Programming of the fail-safe safety controller on an S7-400 H system for the Werdhölzli sludge incineration plant." },
    { title: "Safety controller – sludge incineration", technologies: ["S7-400 H", "Safety"], description: "Programming of the fail-safe safety controller on an S7-400 H system for the Werdhölzli sludge incineration plant." },
    { title: "Control programming – ARA Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Control programming of the ARA Buchs ZH wastewater plant (S7/WinCC OA)." },
    { title: "Grid line MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Welding"], description: "Software development and commissioning of the MG630 grid line." },
    { title: "Radiator line – Celikpan", technologies: ["Siemens S7", "Welding"], description: "Software development and commissioning of the radiator line." },
    { title: "Radiator line – TIPRO Baltic", technologies: ["Siemens S7", "Welding"], description: "Software development and commissioning of the radiator line." },
    { title: "Radiator line – Lida-Baltia", technologies: ["Siemens S7", "Welding"], description: "Software development and commissioning of the radiator line." },
    { title: "Welding control Superflex (Jäger)", technologies: ["Siemens", "TCW welding processor"], description: "Welding control on a Superflex (Jäger) using Siemens and a TCW welding processor." },
    { title: "Grid line Gerdau – S5 → S7 conversion", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion of the grid line from S5 to S7 control." },
    { title: "Grid line MG320 BDW – S5 → S7 conversion", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion of the MG320 grid line from S5 to S7 control." },
    { title: "MG320 conversion S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion of an MG320 from S5 to S7 control." },
    { title: "Software extension – cold-drawing plant", technologies: ["Siemens S7"], description: "Software extension of a cold-drawing plant." },
    { title: "Kieswerk Birr gravel works – WinCC Unified visualization", technologies: ["WinCC Unified", "PC Runtime", "Visualization"], description: "New plant visualization for the Kieswerk Birr gravel works, implemented on WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – WinCC Unified visualization", technologies: ["WinCC Unified", "PC Runtime", "Visualization"], description: "Plant visualization for the gravel works of KIBAG Kies Schafisheim AG, implemented on WinCC Unified PC Runtime." },
    { title: "WinCC Unified modernization – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migration"], description: "Modernization of an existing visualization by migrating from WinCC Advanced to WinCC Unified." },
    { title: "KIBAG vehicle wash bay", technologies: ["WinCC Unified", "Comfort Panel", "Automation"], description: "Control and visualization of a KIBAG vehicle wash bay on a WinCC Unified Comfort Panel." },
    { title: "ARA Rorbas – DALI lighting control", technologies: ["DALI", "Lighting", "Communication"], description: "Implementation of the lighting control for the ARA Rorbas ZH wastewater plant via the DALI bus. Realized on behalf of Rittmeyer." },
    { title: "ARA Lenzerheide – biology & ventilation", technologies: ["Siemens S7", "WinCC OA", "HVAC"], description: "Programming of the control system for biology and ventilation of the Lenzerheide wastewater plant." },
    { title: "EKZ Dietikon run-of-river power plant – trash rake", technologies: ["Siemens S7", "Automation"], description: "Control of the trash rake for the EKZ Dietikon run-of-river power plant." },
    { title: "ARA Lucens – pumping stations & outlying structures", technologies: ["Siemens S7", "WinCC OA"], description: "Software for four outlying structures (pumping stations) of the ARA Lucens wastewater plant plus visualization on WinCC OA. Realized on behalf of Rittmeyer." },
  ],
  es: [
    { title: "EKZ – Alumbrado público, cantón de Zúrich", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Control de iluminación central y seguro para la compañía eléctrica del cantón de Zúrich (EKZ): unos 3000 PLC (SIMATIC S7-1500) en más de 2500 estaciones transformadoras, controlados con WinCC OA SCADA y programados en TIA Portal. Comunicación OPC UA cifrada, incl. OPC UA GDS Push para la gestión central de certificados. Realizado con Siemens Schweiz DI AG." },
    { title: "Centro de distribución Mix-Mail – Correos de Suiza", technologies: ["Siemens", "Clasificador cross-belt", "Transporte", "Automatización"], description: "Desarrollo de software para la clasificación totalmente automática de envíos mixtos (Mix-Mail): una novedad mundial en clasificación. Capacidad de hasta 19 000 envíos por hora, aprox. 1400 destinos y 5 clasificadores cross-belt en dos niveles. Realizado con Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Basilea – nuevo centro logístico", technologies: ["Siemens", "Transporte", "Automatización"], description: "Desarrollo de software para un centro logístico completo de DHL Express: conceptos de control, automatización y software específico de instalación y aplicación. Responsable de la tecnología de transporte con más de 500 cintas, clasificadores y destinos; capacidad de clasificación de unos 10 000 envíos por hora. Realizado con Siemens Logistics AG." },
    { title: "ARA Zermatt – mayor planta de biología de membrana de Suiza", technologies: ["Siemens S7", "WinCC OA", "HVAC", "SCADA"], description: "Reprogramación de toda la depuradora, incl. climatización: la mayor planta de biología de membrana de Suiza, en una caverna en el interior de la montaña. Control con más de 10 CPU SIMATIC (STEP 7) y WinCC OA como sistema SCADA; tamaño de diseño 60 000 habitantes equivalentes." },
    { title: "SBB – carro transversal 360°, Zúrich Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Actualización del PLC existente de STEP 7 a TIA Portal, incl. adaptación de software para el desplazamiento del carro transversal con función de 360 grados. Realizado con Siemens Schweiz DI AG." },
    { title: "Equinix – ampliación de centro de datos", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Ampliación de un centro de datos existente con una nueva planta, incl. sistema de generadores; procesamiento de datos mediante Modbus RTU y TCP. Realizado con Siemens Schweiz DI AG." },
    { title: "Equinix – actualización de PCS 7 a V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Actualización de un proyecto de centro de datos existente a SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizado con Siemens Schweiz DI AG." },
    { title: "Equinix – actualización de PCS 7 a V9.1 (2.ª ubicación)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Actualización de otro proyecto de centro de datos existente a SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizado con Siemens Schweiz DI AG." },
    { title: "Control de tanque de tormenta – ARA Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para varios tanques de tormenta (TIA Portal/WinCC OA)." },
    { title: "Planta de recuperación de calor de aguas residuales – ARA Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Ampliación del control de la planta de recuperación de calor de aguas residuales (S7/WinCC OA)." },
    { title: "Control de tanque de tormenta – Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Planta de recuperación de calor de aguas residuales – ARA Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la planta de recuperación de calor de aguas residuales (S7/WinCC OA)." },
    { title: "Planta de recuperación de calor de aguas residuales – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la planta de recuperación de calor de aguas residuales (S7/WinCC OA)." },
    { title: "Planta de recuperación de calor de aguas residuales – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la planta de recuperación de calor de aguas residuales (S7/WinCC OA)." },
    { title: "Planta de recuperación de calor de aguas residuales – ARA Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la planta de recuperación de calor de aguas residuales (S7/WinCC OA)." },
    { title: "Control de tanque de tormenta – Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control para un tanque de tormenta (TIA Portal/WinCC OA)." },
    { title: "Control de tanque de tormenta – ARA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control para un tanque de tormenta (S7/WinCC OA)." },
    { title: "Estación de abastecimiento de agua Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Programación del control de una estación de abastecimiento de agua (TIA Portal/WinCC OA)." },
    { title: "Depuradora Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la depuradora (S7/WinCC OA)." },
    { title: "Sistema de ventilación y calefacción – ARA Zermatt", technologies: ["Siemens S7", "HVAC"], description: "Programación del sistema de ventilación y calefacción de la depuradora de Zermatt." },
    { title: "Control de seguridad – incineración de lodos", technologies: ["S7-400 H", "Safety"], description: "Programación del control de seguridad a prueba de fallos en un sistema S7-400 H para la planta de incineración de lodos de Werdhölzli." },
    { title: "Control de seguridad – incineración de lodos", technologies: ["S7-400 H", "Safety"], description: "Programación del control de seguridad a prueba de fallos en un sistema S7-400 H para la planta de incineración de lodos de Werdhölzli." },
    { title: "Programación de control – ARA Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Programación del control de la depuradora ARA Buchs ZH (S7/WinCC OA)." },
    { title: "Línea de mallas MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Soldadura"], description: "Desarrollo de software y puesta en marcha de la línea de mallas MG630." },
    { title: "Línea de radiadores – Celikpan", technologies: ["Siemens S7", "Soldadura"], description: "Desarrollo de software y puesta en marcha de la línea de radiadores." },
    { title: "Línea de radiadores – TIPRO Baltic", technologies: ["Siemens S7", "Soldadura"], description: "Desarrollo de software y puesta en marcha de la línea de radiadores." },
    { title: "Línea de radiadores – Lida-Baltia", technologies: ["Siemens S7", "Soldadura"], description: "Desarrollo de software y puesta en marcha de la línea de radiadores." },
    { title: "Control de soldadura Superflex (Jäger)", technologies: ["Siemens", "Procesador de soldadura TCW"], description: "Control de soldadura en una Superflex (Jäger) con Siemens y procesador de soldadura TCW." },
    { title: "Línea de mallas Gerdau – conversión S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversión de la línea de mallas de control S5 a S7." },
    { title: "Línea de mallas MG320 BDW – conversión S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversión de la línea de mallas MG320 de control S5 a S7." },
    { title: "Conversión MG320 S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversión de una MG320 de control S5 a S7." },
    { title: "Ampliación de software – planta de estirado en frío", technologies: ["Siemens S7"], description: "Ampliación de software de una planta de estirado en frío." },
    { title: "Planta de grava Birr – visualización WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualización"], description: "Nueva visualización de la planta de grava de Birr, implementada en WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – visualización WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualización"], description: "Visualización de la planta de grava de KIBAG Kies Schafisheim AG, implementada en WinCC Unified PC Runtime." },
    { title: "Modernización WinCC Unified – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migración"], description: "Modernización de una visualización existente mediante la migración de WinCC Advanced a WinCC Unified." },
    { title: "KIBAG – área de lavado de vehículos", technologies: ["WinCC Unified", "Comfort Panel", "Automatización"], description: "Control y visualización de un área de lavado de vehículos de KIBAG en un WinCC Unified Comfort Panel." },
    { title: "ARA Rorbas – control de iluminación DALI", technologies: ["DALI", "Iluminación", "Comunicación"], description: "Implementación del control de iluminación de la depuradora ARA Rorbas ZH mediante el bus DALI. Realizado por encargo de Rittmeyer." },
    { title: "ARA Lenzerheide – biología y ventilación", technologies: ["Siemens S7", "WinCC OA", "HVAC"], description: "Programación del control para la biología y la ventilación de la depuradora de Lenzerheide." },
    { title: "Central hidroeléctrica EKZ Dietikon – reja de limpieza", technologies: ["Siemens S7", "Automatización"], description: "Control de la reja de limpieza para la central hidroeléctrica de EKZ en Dietikon." },
    { title: "ARA Lucens – estaciones de bombeo y obras exteriores", technologies: ["Siemens S7", "WinCC OA"], description: "Software para cuatro obras exteriores (estaciones de bombeo) de la depuradora ARA Lucens y visualización en WinCC OA. Realizado por encargo de Rittmeyer." },
  ],
  fr: [
    { title: "EKZ – Éclairage public, canton de Zurich", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Commande d'éclairage centrale et sécurisée pour le fournisseur d'électricité du canton de Zurich (EKZ) : environ 3000 API (SIMATIC S7-1500) dans plus de 2500 postes de transformation, pilotés avec WinCC OA SCADA et programmés dans TIA Portal. Communication OPC UA chiffrée, y compris OPC UA GDS Push pour la gestion centrale des certificats. Réalisé avec Siemens Schweiz DI AG." },
    { title: "Centre de tri Mix-Mail – La Poste suisse", technologies: ["Siemens", "Trieur cross-belt", "Convoyage", "Automatisation"], description: "Développement logiciel pour le tri entièrement automatique d'envois mixtes (Mix-Mail) : une première mondiale en matière de tri. Capacité jusqu'à 19 000 envois par heure, environ 1400 exutoires et 5 trieurs cross-belt sur deux niveaux. Réalisé avec Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Bâle – nouveau centre logistique", technologies: ["Siemens", "Convoyage", "Automatisation"], description: "Développement logiciel pour un centre logistique complet de DHL Express : concepts de commande, d'automatisation et logiciels spécifiques à l'installation et à l'application. Responsable du convoyage avec plus de 500 convoyeurs, trieurs et exutoires ; capacité de tri d'environ 10 000 envois par heure. Réalisé avec Siemens Logistics AG." },
    { title: "STEP Zermatt – plus grande installation de biologie membranaire de Suisse", technologies: ["Siemens S7", "WinCC OA", "CVC", "SCADA"], description: "Reprogrammation de toute la station d'épuration, CVC compris : la plus grande installation de biologie membranaire de Suisse, dans une caverne à l'intérieur de la montagne. Commande avec plus de 10 CPU SIMATIC (STEP 7) et WinCC OA comme système SCADA ; capacité 60 000 équivalents-habitants." },
    { title: "CFF – chariot transversal 360°, Zurich Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Mise à niveau de l'API existant de STEP 7 vers TIA Portal avec adaptation logicielle pour le déplacement du chariot transversal avec fonction 360 degrés. Réalisé avec Siemens Schweiz DI AG." },
    { title: "Equinix – extension de centre de données", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Extension d'un centre de données existant avec un nouvel étage et un système de générateurs ; traitement des données via Modbus RTU et TCP. Réalisé avec Siemens Schweiz DI AG." },
    { title: "Equinix – mise à niveau de PCS 7 vers V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Mise à niveau d'un projet de centre de données existant vers SIMATIC PCS 7 V9.1 (PH et IF compris). Réalisé avec Siemens Schweiz DI AG." },
    { title: "Equinix – mise à niveau de PCS 7 vers V9.1 (2e site)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Mise à niveau d'un autre projet de centre de données existant vers SIMATIC PCS 7 V9.1 (PH et IF compris). Réalisé avec Siemens Schweiz DI AG." },
    { title: "Commande de bassin d'orage – STEP Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour plusieurs bassins d'orage (TIA Portal/WinCC OA)." },
    { title: "Installation de récupération de chaleur des eaux usées – STEP Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Extension de la commande de l'installation de récupération de chaleur des eaux usées (S7/WinCC OA)." },
    { title: "Commande de bassin d'orage – Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Installation de récupération de chaleur des eaux usées – STEP Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de l'installation de récupération de chaleur des eaux usées (S7/WinCC OA)." },
    { title: "Installation de récupération de chaleur des eaux usées – STEP Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de l'installation de récupération de chaleur des eaux usées (S7/WinCC OA)." },
    { title: "Installation de récupération de chaleur des eaux usées – STEP Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de l'installation de récupération de chaleur des eaux usées (S7/WinCC OA)." },
    { title: "Installation de récupération de chaleur des eaux usées – STEP Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de l'installation de récupération de chaleur des eaux usées (S7/WinCC OA)." },
    { title: "Commande de bassin d'orage – Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (TIA Portal/WinCC OA)." },
    { title: "Commande de bassin d'orage – STEP Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande pour un bassin d'orage (S7/WinCC OA)." },
    { title: "Station de pompage d'eau Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Programmation de la commande d'une station de pompage d'eau (TIA Portal/WinCC OA)." },
    { title: "Station d'épuration Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de la station d'épuration (S7/WinCC OA)." },
    { title: "Système de ventilation et de chauffage – STEP Zermatt", technologies: ["Siemens S7", "CVC"], description: "Programmation du système de ventilation et de chauffage de la station d'épuration de Zermatt." },
    { title: "Commande de sécurité – incinération des boues", technologies: ["S7-400 H", "Safety"], description: "Programmation de la commande de sécurité à sécurité intégrée sur un système S7-400 H pour l'installation d'incinération des boues de Werdhölzli." },
    { title: "Commande de sécurité – incinération des boues", technologies: ["S7-400 H", "Safety"], description: "Programmation de la commande de sécurité à sécurité intégrée sur un système S7-400 H pour l'installation d'incinération des boues de Werdhölzli." },
    { title: "Programmation de commande – STEP Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Programmation de la commande de la station d'épuration STEP Buchs ZH (S7/WinCC OA)." },
    { title: "Ligne de treillis MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Soudage"], description: "Développement logiciel et mise en service de la ligne de treillis MG630." },
    { title: "Ligne de radiateurs – Celikpan", technologies: ["Siemens S7", "Soudage"], description: "Développement logiciel et mise en service de la ligne de radiateurs." },
    { title: "Ligne de radiateurs – TIPRO Baltic", technologies: ["Siemens S7", "Soudage"], description: "Développement logiciel et mise en service de la ligne de radiateurs." },
    { title: "Ligne de radiateurs – Lida-Baltia", technologies: ["Siemens S7", "Soudage"], description: "Développement logiciel et mise en service de la ligne de radiateurs." },
    { title: "Commande de soudage Superflex (Jäger)", technologies: ["Siemens", "Processeur de soudage TCW"], description: "Commande de soudage sur une Superflex (Jäger) avec Siemens et processeur de soudage TCW." },
    { title: "Ligne de treillis Gerdau – conversion S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion de la ligne de treillis de la commande S5 vers S7." },
    { title: "Ligne de treillis MG320 BDW – conversion S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion de la ligne de treillis MG320 de la commande S5 vers S7." },
    { title: "Conversion MG320 S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversion d'une MG320 de la commande S5 vers S7." },
    { title: "Extension logicielle – ligne d'étirage à froid", technologies: ["Siemens S7"], description: "Extension logicielle d'une ligne d'étirage à froid." },
    { title: "Gravière de Birr – visualisation WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualisation"], description: "Nouvelle visualisation de l'installation pour la gravière de Birr, réalisée sur WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – visualisation WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualisation"], description: "Visualisation de l'installation pour la gravière de KIBAG Kies Schafisheim AG, réalisée sur WinCC Unified PC Runtime." },
    { title: "Modernisation WinCC Unified – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migration"], description: "Modernisation d'une visualisation existante par migration de WinCC Advanced vers WinCC Unified." },
    { title: "KIBAG – aire de lavage de véhicules", technologies: ["WinCC Unified", "Comfort Panel", "Automatisation"], description: "Commande et visualisation d'une aire de lavage de véhicules de KIBAG sur un WinCC Unified Comfort Panel." },
    { title: "STEP Rorbas – commande d'éclairage DALI", technologies: ["DALI", "Éclairage", "Communication"], description: "Réalisation de la commande d'éclairage de la station d'épuration de Rorbas ZH via le bus DALI. Réalisé pour le compte de Rittmeyer." },
    { title: "STEP Lenzerheide – biologie et ventilation", technologies: ["Siemens S7", "WinCC OA", "CVC"], description: "Programmation de la commande pour la biologie et la ventilation de la station d'épuration de Lenzerheide." },
    { title: "Centrale au fil de l'eau EKZ Dietikon – dégrilleur", technologies: ["Siemens S7", "Automatisation"], description: "Commande du dégrilleur pour la centrale au fil de l'eau d'EKZ à Dietikon." },
    { title: "STEP Lucens – stations de pompage et ouvrages extérieurs", technologies: ["Siemens S7", "WinCC OA"], description: "Logiciel pour quatre ouvrages extérieurs (stations de pompage) de la station d'épuration de Lucens ainsi que visualisation sur WinCC OA. Réalisé pour le compte de Rittmeyer." },
  ],
  it: [
    { title: "EKZ – Illuminazione pubblica, Cantone di Zurigo", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Comando di illuminazione centrale e sicuro per l'azienda elettrica del Cantone di Zurigo (EKZ): circa 3000 PLC (SIMATIC S7-1500) in oltre 2500 cabine di trasformazione, comandati con WinCC OA SCADA e programmati in TIA Portal. Comunicazione OPC UA cifrata, incl. OPC UA GDS Push per la gestione centralizzata dei certificati. Realizzato con Siemens Schweiz DI AG." },
    { title: "Centro di smistamento Mix-Mail – Posta svizzera", technologies: ["Siemens", "Sorter cross-belt", "Trasporto", "Automazione"], description: "Sviluppo software per lo smistamento completamente automatico di invii misti (Mix-Mail): una novità mondiale nello smistamento. Capacità fino a 19 000 invii all'ora, circa 1400 scivoli e 5 sorter cross-belt su due livelli. Realizzato con Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Basilea – nuovo centro logistico", technologies: ["Siemens", "Trasporto", "Automazione"], description: "Sviluppo software per un centro logistico completo di DHL Express: concetti di comando, automazione e software specifico per impianto e applicazione. Responsabile della tecnica di trasporto con oltre 500 nastri, sorter e scivoli; capacità di smistamento di circa 10 000 invii all'ora. Realizzato con Siemens Logistics AG." },
    { title: "IDA Zermatt – maggiore impianto a biologia a membrana della Svizzera", technologies: ["Siemens S7", "WinCC OA", "HVAC", "SCADA"], description: "Riprogrammazione dell'intero impianto di depurazione, incl. HVAC: il maggiore impianto a biologia a membrana della Svizzera, in una caverna all'interno della montagna. Comando con oltre 10 CPU SIMATIC (STEP 7) e WinCC OA come sistema SCADA; dimensionamento 60 000 abitanti equivalenti." },
    { title: "FFS – carro trasversale 360°, Zurigo Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Aggiornamento del PLC esistente da STEP 7 a TIA Portal, incl. adattamento software per lo spostamento del carro trasversale con funzione a 360 gradi. Realizzato con Siemens Schweiz DI AG." },
    { title: "Equinix – ampliamento di data center", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Ampliamento di un data center esistente con un nuovo piano e un sistema di generatori; elaborazione dati tramite Modbus RTU e TCP. Realizzato con Siemens Schweiz DI AG." },
    { title: "Equinix – aggiornamento di PCS 7 a V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Aggiornamento di un progetto di data center esistente a SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizzato con Siemens Schweiz DI AG." },
    { title: "Equinix – aggiornamento di PCS 7 a V9.1 (2° sito)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Aggiornamento di un altro progetto di data center esistente a SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizzato con Siemens Schweiz DI AG." },
    { title: "Comando bacino di pioggia – IDA Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per diversi bacini di pioggia (TIA Portal/WinCC OA)." },
    { title: "Impianto di recupero calore delle acque reflue – IDA Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Ampliamento del comando dell'impianto di recupero calore delle acque reflue (S7/WinCC OA)." },
    { title: "Comando bacino di pioggia – Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Impianto di recupero calore delle acque reflue – IDA Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di recupero calore delle acque reflue (S7/WinCC OA)." },
    { title: "Impianto di recupero calore delle acque reflue – IDA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di recupero calore delle acque reflue (S7/WinCC OA)." },
    { title: "Impianto di recupero calore delle acque reflue – IDA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di recupero calore delle acque reflue (S7/WinCC OA)." },
    { title: "Impianto di recupero calore delle acque reflue – IDA Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di recupero calore delle acque reflue (S7/WinCC OA)." },
    { title: "Comando bacino di pioggia – Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (TIA Portal/WinCC OA)." },
    { title: "Comando bacino di pioggia – IDA Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando per un bacino di pioggia (S7/WinCC OA)." },
    { title: "Stazione di pompaggio acqua Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Programmazione del comando di una stazione di pompaggio acqua (TIA Portal/WinCC OA)." },
    { title: "Impianto di depurazione Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di depurazione (S7/WinCC OA)." },
    { title: "Sistema di ventilazione e riscaldamento – IDA Zermatt", technologies: ["Siemens S7", "HVAC"], description: "Programmazione del sistema di ventilazione e riscaldamento dell'impianto di depurazione di Zermatt." },
    { title: "Controllo di sicurezza – incenerimento fanghi", technologies: ["S7-400 H", "Safety"], description: "Programmazione del controllo di sicurezza fail-safe su sistema S7-400 H per l'impianto di incenerimento fanghi di Werdhölzli." },
    { title: "Controllo di sicurezza – incenerimento fanghi", technologies: ["S7-400 H", "Safety"], description: "Programmazione del controllo di sicurezza fail-safe su sistema S7-400 H per l'impianto di incenerimento fanghi di Werdhölzli." },
    { title: "Programmazione comando – IDA Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Programmazione del comando dell'impianto di depurazione IDA Buchs ZH (S7/WinCC OA)." },
    { title: "Linea di reti MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Saldatura"], description: "Sviluppo software e messa in servizio della linea di reti MG630." },
    { title: "Linea di radiatori – Celikpan", technologies: ["Siemens S7", "Saldatura"], description: "Sviluppo software e messa in servizio della linea di radiatori." },
    { title: "Linea di radiatori – TIPRO Baltic", technologies: ["Siemens S7", "Saldatura"], description: "Sviluppo software e messa in servizio della linea di radiatori." },
    { title: "Linea di radiatori – Lida-Baltia", technologies: ["Siemens S7", "Saldatura"], description: "Sviluppo software e messa in servizio della linea di radiatori." },
    { title: "Comando di saldatura Superflex (Jäger)", technologies: ["Siemens", "Processore di saldatura TCW"], description: "Comando di saldatura su una Superflex (Jäger) con Siemens e processore di saldatura TCW." },
    { title: "Linea di reti Gerdau – conversione S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversione della linea di reti dal comando S5 a S7." },
    { title: "Linea di reti MG320 BDW – conversione S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversione della linea di reti MG320 dal comando S5 a S7." },
    { title: "Conversione MG320 S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversione di una MG320 dal comando S5 a S7." },
    { title: "Estensione software – linea di trafilatura a freddo", technologies: ["Siemens S7"], description: "Estensione software di una linea di trafilatura a freddo." },
    { title: "Cava di ghiaia Birr – visualizzazione WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualizzazione"], description: "Nuova visualizzazione dell'impianto per la cava di ghiaia di Birr, realizzata su WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – visualizzazione WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualizzazione"], description: "Visualizzazione dell'impianto per la cava di ghiaia di KIBAG Kies Schafisheim AG, realizzata su WinCC Unified PC Runtime." },
    { title: "Modernizzazione WinCC Unified – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migrazione"], description: "Modernizzazione di una visualizzazione esistente mediante migrazione da WinCC Advanced a WinCC Unified." },
    { title: "KIBAG – area di lavaggio veicoli", technologies: ["WinCC Unified", "Comfort Panel", "Automazione"], description: "Comando e visualizzazione di un'area di lavaggio veicoli di KIBAG su un WinCC Unified Comfort Panel." },
    { title: "IDA Rorbas – comando di illuminazione DALI", technologies: ["DALI", "Illuminazione", "Comunicazione"], description: "Realizzazione del comando di illuminazione dell'impianto di depurazione di Rorbas ZH tramite il bus DALI. Realizzato per conto di Rittmeyer." },
    { title: "IDA Lenzerheide – biologia e ventilazione", technologies: ["Siemens S7", "WinCC OA", "HVAC"], description: "Programmazione del comando per la biologia e la ventilazione dell'impianto di depurazione di Lenzerheide." },
    { title: "Centrale ad acqua fluente EKZ Dietikon – griglia di pulizia", technologies: ["Siemens S7", "Automazione"], description: "Comando della griglia di pulizia per la centrale ad acqua fluente di EKZ a Dietikon." },
    { title: "IDA Lucens – stazioni di pompaggio e opere esterne", technologies: ["Siemens S7", "WinCC OA"], description: "Software per quattro opere esterne (stazioni di pompaggio) dell'impianto di depurazione di Lucens e visualizzazione su WinCC OA. Realizzato per conto di Rittmeyer." },
  ],
  pt: [
    { title: "EKZ – Iluminação pública, cantão de Zurique", technologies: ["WinCC OA", "TIA Portal", "S7-1500", "OPC UA", "OPC UA GDS Push"], description: "Comando de iluminação central e seguro para a empresa de eletricidade do cantão de Zurique (EKZ): cerca de 3000 PLC (SIMATIC S7-1500) em mais de 2500 postos de transformação, comandados com WinCC OA SCADA e programados em TIA Portal. Comunicação OPC UA cifrada, incl. OPC UA GDS Push para a gestão central de certificados. Realizado com Siemens Schweiz DI AG." },
    { title: "Centro de distribuição Mix-Mail – Correios da Suíça", technologies: ["Siemens", "Sorter cross-belt", "Transporte", "Automação"], description: "Desenvolvimento de software para a triagem totalmente automática de envios mistos (Mix-Mail): uma novidade mundial na triagem. Capacidade até 19 000 envios por hora, cerca de 1400 destinos e 5 sorters cross-belt em dois níveis. Realizado com Siemens Postal, Parcel & Airport Logistics." },
    { title: "DHL Gateway Basileia – novo centro logístico", technologies: ["Siemens", "Transporte", "Automação"], description: "Desenvolvimento de software para um centro logístico completo da DHL Express: conceitos de comando, automação e software específico de instalação e aplicação. Responsável pela tecnologia de transporte com mais de 500 tapetes, sorters e destinos; capacidade de triagem de cerca de 10 000 envios por hora. Realizado com Siemens Logistics AG." },
    { title: "ETAR Zermatt – maior instalação de biologia de membrana da Suíça", technologies: ["Siemens S7", "WinCC OA", "AVAC", "SCADA"], description: "Reprogramação de toda a estação de tratamento, incl. AVAC: a maior instalação de biologia de membrana da Suíça, numa caverna no interior da montanha. Comando com mais de 10 CPU SIMATIC (STEP 7) e WinCC OA como sistema SCADA; dimensionamento 60 000 habitantes equivalentes." },
    { title: "SBB – vagão transversal 360°, Zurique Altstetten", technologies: ["STEP 7", "TIA Portal"], description: "Atualização do PLC existente de STEP 7 para TIA Portal, incl. adaptação de software para a deslocação do vagão transversal com função de 360 graus. Realizado com Siemens Schweiz DI AG." },
    { title: "Equinix – ampliação de centro de dados", technologies: ["PCS 7", "Modbus RTU", "Modbus TCP"], description: "Ampliação de um centro de dados existente com um novo piso e um sistema de geradores; processamento de dados via Modbus RTU e TCP. Realizado com Siemens Schweiz DI AG." },
    { title: "Equinix – atualização de PCS 7 para V9.1", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Atualização de um projeto de centro de dados existente para SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizado com Siemens Schweiz DI AG." },
    { title: "Equinix – atualização de PCS 7 para V9.1 (2.º local)", technologies: ["PCS 7 V9.1", "PH", "IF"], description: "Atualização de outro projeto de centro de dados existente para SIMATIC PCS 7 V9.1 (incl. PH e IF). Realizado com Siemens Schweiz DI AG." },
    { title: "Comando de bacia de tempestade – ETAR Reinach", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para várias bacias de tempestade (TIA Portal/WinCC OA)." },
    { title: "Instalação de recuperação de calor de águas residuais – ETAR Elgg", technologies: ["Siemens S7", "WinCC OA"], description: "Ampliação do comando da instalação de recuperação de calor de águas residuais (S7/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Sennhof", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Huggenberg", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Dickbuch", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Hauptwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Niederwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Instalação de recuperação de calor de águas residuais – ETAR Lugano", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da instalação de recuperação de calor de águas residuais (S7/WinCC OA)." },
    { title: "Instalação de recuperação de calor de águas residuais – ETAR Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da instalação de recuperação de calor de águas residuais (S7/WinCC OA)." },
    { title: "Instalação de recuperação de calor de águas residuais – ETAR Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da instalação de recuperação de calor de águas residuais (S7/WinCC OA)." },
    { title: "Instalação de recuperação de calor de águas residuais – ETAR Oensingen", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da instalação de recuperação de calor de águas residuais (S7/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Arnegg", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – Andwil", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (TIA Portal/WinCC OA)." },
    { title: "Comando de bacia de tempestade – ETAR Zermatt", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando para uma bacia de tempestade (S7/WinCC OA)." },
    { title: "Estação de bombagem de água Henessen", technologies: ["TIA Portal", "WinCC OA"], description: "Programação do comando de uma estação de bombagem de água (TIA Portal/WinCC OA)." },
    { title: "Estação de tratamento de águas residuais Rheinfelden", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da estação de tratamento de águas residuais (S7/WinCC OA)." },
    { title: "Sistema de ventilação e aquecimento – ETAR Zermatt", technologies: ["Siemens S7", "AVAC"], description: "Programação do sistema de ventilação e aquecimento da estação de tratamento de Zermatt." },
    { title: "Controlo de segurança – incineração de lamas", technologies: ["S7-400 H", "Safety"], description: "Programação do controlo de segurança à prova de falhas num sistema S7-400 H para a instalação de incineração de lamas de Werdhölzli." },
    { title: "Controlo de segurança – incineração de lamas", technologies: ["S7-400 H", "Safety"], description: "Programação do controlo de segurança à prova de falhas num sistema S7-400 H para a instalação de incineração de lamas de Werdhölzli." },
    { title: "Programação de comando – ETAR Buchs", technologies: ["Siemens S7", "WinCC OA"], description: "Programação do comando da estação de tratamento ETAR Buchs ZH (S7/WinCC OA)." },
    { title: "Linha de redes MG630 – TALLERES Y ACEROS", technologies: ["Siemens S7", "Soldadura"], description: "Desenvolvimento de software e colocação em serviço da linha de redes MG630." },
    { title: "Linha de radiadores – Celikpan", technologies: ["Siemens S7", "Soldadura"], description: "Desenvolvimento de software e colocação em serviço da linha de radiadores." },
    { title: "Linha de radiadores – TIPRO Baltic", technologies: ["Siemens S7", "Soldadura"], description: "Desenvolvimento de software e colocação em serviço da linha de radiadores." },
    { title: "Linha de radiadores – Lida-Baltia", technologies: ["Siemens S7", "Soldadura"], description: "Desenvolvimento de software e colocação em serviço da linha de radiadores." },
    { title: "Comando de soldadura Superflex (Jäger)", technologies: ["Siemens", "Processador de soldadura TCW"], description: "Comando de soldadura numa Superflex (Jäger) com Siemens e processador de soldadura TCW." },
    { title: "Linha de redes Gerdau – conversão S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversão da linha de redes do comando S5 para S7." },
    { title: "Linha de redes MG320 BDW – conversão S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversão da linha de redes MG320 do comando S5 para S7." },
    { title: "Conversão MG320 S5 → S7", technologies: ["Siemens S5", "Siemens S7"], description: "Conversão de uma MG320 do comando S5 para S7." },
    { title: "Ampliação de software – linha de trefilagem a frio", technologies: ["Siemens S7"], description: "Ampliação de software de uma linha de trefilagem a frio." },
    { title: "Cascalheira Birr – visualização WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualização"], description: "Nova visualização da instalação para a cascalheira de Birr, implementada em WinCC Unified PC Runtime." },
    { title: "KIBAG Kies Schafisheim – visualização WinCC Unified", technologies: ["WinCC Unified", "PC Runtime", "Visualização"], description: "Visualização da instalação para a cascalheira da KIBAG Kies Schafisheim AG, implementada em WinCC Unified PC Runtime." },
    { title: "Modernização WinCC Unified – Advanced → Unified", technologies: ["WinCC Unified", "WinCC Advanced", "Migração"], description: "Modernização de uma visualização existente através da migração de WinCC Advanced para WinCC Unified." },
    { title: "KIBAG – zona de lavagem de veículos", technologies: ["WinCC Unified", "Comfort Panel", "Automação"], description: "Comando e visualização de uma zona de lavagem de veículos da KIBAG num WinCC Unified Comfort Panel." },
    { title: "ETAR Rorbas – controlo de iluminação DALI", technologies: ["DALI", "Iluminação", "Comunicação"], description: "Implementação do controlo de iluminação da estação de tratamento de Rorbas ZH através do bus DALI. Realizado por conta da Rittmeyer." },
    { title: "ETAR Lenzerheide – biologia e ventilação", technologies: ["Siemens S7", "WinCC OA", "AVAC"], description: "Programação do comando para a biologia e a ventilação da estação de tratamento de Lenzerheide." },
    { title: "Central a fio de água EKZ Dietikon – grade de limpeza", technologies: ["Siemens S7", "Automação"], description: "Comando da grade de limpeza para a central a fio de água da EKZ em Dietikon." },
    { title: "ETAR Lucens – estações de bombagem e obras exteriores", technologies: ["Siemens S7", "WinCC OA"], description: "Software para quatro obras exteriores (estações de bombagem) da estação de tratamento de Lucens e visualização em WinCC OA. Realizado por conta da Rittmeyer." },
  ],
};

const categoryLabelsByLocale: Record<Locale, Record<ProjectCategory, string>> = {
  de: {
    infrastruktur: "Infrastruktur & Energie",
    logistik: "Logistik & Sortieranlagen",
    abwasser: "Abwasser & ARA",
    stahl: "Stahl- & Industrieanlagen",
    retrofit: "Retrofit & Migration",
    kies: "Kies & Aufbereitung",
    kommunikation: "Kommunikation",
  },
  en: {
    infrastruktur: "Infrastructure & energy",
    logistik: "Logistics & sorting",
    abwasser: "Wastewater & WWTP",
    stahl: "Steel & industrial plants",
    retrofit: "Retrofit & migration",
    kies: "Gravel & processing",
    kommunikation: "Communication",
  },
  es: {
    infrastruktur: "Infraestructura y energía",
    logistik: "Logística y clasificación",
    abwasser: "Aguas residuales y EDAR",
    stahl: "Instalaciones siderúrgicas e industriales",
    retrofit: "Retrofit y migración",
    kies: "Grava y tratamiento",
    kommunikation: "Comunicación",
  },
  fr: {
    infrastruktur: "Infrastructure et énergie",
    logistik: "Logistique et tri",
    abwasser: "Eaux usées et STEP",
    stahl: "Installations sidérurgiques et industrielles",
    retrofit: "Rétrofit et migration",
    kies: "Gravier et traitement",
    kommunikation: "Communication",
  },
  it: {
    infrastruktur: "Infrastruttura ed energia",
    logistik: "Logistica e smistamento",
    abwasser: "Acque reflue e IDA",
    stahl: "Impianti siderurgici e industriali",
    retrofit: "Retrofit e migrazione",
    kies: "Ghiaia e trattamento",
    kommunikation: "Comunicazione",
  },
  pt: {
    infrastruktur: "Infraestrutura e energia",
    logistik: "Logística e triagem",
    abwasser: "Águas residuais e ETAR",
    stahl: "Instalações siderúrgicas e industriais",
    retrofit: "Retrofit e migração",
    kies: "Cascalho e processamento",
    kommunikation: "Comunicação",
  },
};

const highlightsByLocale: Record<Locale, { category: ProjectCategory; description: string }[]> = {
  de: [
    { category: "infrastruktur", description: "Kritische Infrastruktur und Energie: öffentliche Beleuchtung (EKZ) und Rechenzentren (Equinix) – mit WinCC OA, TIA Portal, PCS 7 und OPC UA." },
    { category: "logistik", description: "Software-Entwicklung für Paket- und Mischsendungs-Sortieranlagen – u. a. für DHL Express und die Schweizerische Post." },
    { category: "abwasser", description: "ARA-Projekte, Regenbecken, Abwasserwärmerückgewinnung und Sicherheitssteuerungen in der ganzen Schweiz." },
    { category: "stahl", description: "Internationale Inbetriebnahmen von Stahl- und Industrieanlagen in Europa und Amerika." },
    { category: "retrofit", description: "Modernisierung bestehender Anlagen und Migration von Altsteuerungen (S5 → S7 → TIA) sowie von WinCC Advanced auf WinCC Unified." },
    { category: "kies", description: "Anlagenvisualisierung für Kieswerke auf WinCC Unified – u. a. Kieswerk Birr und KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Bus- und Kommunikationslösungen wie die DALI-Beleuchtungssteuerung der ARA Rorbas." },
  ],
  en: [
    { category: "infrastruktur", description: "Critical infrastructure and energy: public lighting (EKZ) and data centres (Equinix) – with WinCC OA, TIA Portal, PCS 7 and OPC UA." },
    { category: "logistik", description: "Software development for parcel and mixed-mail sorting plants – including for DHL Express and Swiss Post." },
    { category: "abwasser", description: "Wastewater plant projects, stormwater tanks, wastewater heat recovery and safety controllers throughout Switzerland." },
    { category: "stahl", description: "International commissioning of steel and industrial plants in Europe and the Americas." },
    { category: "retrofit", description: "Modernization of existing plants and migration of legacy controllers (S5 → S7 → TIA) and from WinCC Advanced to WinCC Unified." },
    { category: "kies", description: "Plant visualization for gravel works on WinCC Unified – including Kieswerk Birr and KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Bus and communication solutions such as the DALI lighting control at ARA Rorbas." },
  ],
  es: [
    { category: "infrastruktur", description: "Infraestructura crítica y energía: alumbrado público (EKZ) y centros de datos (Equinix), con WinCC OA, TIA Portal, PCS 7 y OPC UA." },
    { category: "logistik", description: "Desarrollo de software para plantas de clasificación de paquetes y envíos mixtos, entre otros para DHL Express y Correos de Suiza." },
    { category: "abwasser", description: "Proyectos de EDAR, tanques de tormenta, recuperación de calor de aguas residuales y controles de seguridad en toda Suiza." },
    { category: "stahl", description: "Puestas en marcha internacionales de instalaciones siderúrgicas e industriales en Europa y América." },
    { category: "retrofit", description: "Modernización de instalaciones existentes y migración de controladores antiguos (S5 → S7 → TIA) y de WinCC Advanced a WinCC Unified." },
    { category: "kies", description: "Visualización de plantas para plantas de grava con WinCC Unified, entre otras Kieswerk Birr y KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Soluciones de bus y comunicación como el control de iluminación DALI de la EDAR Rorbas." },
  ],
  fr: [
    { category: "infrastruktur", description: "Infrastructure critique et énergie : éclairage public (EKZ) et centres de données (Equinix), avec WinCC OA, TIA Portal, PCS 7 et OPC UA." },
    { category: "logistik", description: "Développement logiciel pour des installations de tri de colis et d'envois mixtes, notamment pour DHL Express et La Poste suisse." },
    { category: "abwasser", description: "Projets de STEP, bassins d'orage, récupération de chaleur des eaux usées et commandes de sécurité dans toute la Suisse." },
    { category: "stahl", description: "Mises en service internationales d'installations sidérurgiques et industrielles en Europe et en Amérique." },
    { category: "retrofit", description: "Modernisation d'installations existantes et migration d'anciennes commandes (S5 → S7 → TIA) ainsi que de WinCC Advanced vers WinCC Unified." },
    { category: "kies", description: "Visualisation d'installations pour graviers avec WinCC Unified, dont Kieswerk Birr et KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Solutions de bus et de communication comme la commande d'éclairage DALI de la STEP Rorbas." },
  ],
  it: [
    { category: "infrastruktur", description: "Infrastruttura critica ed energia: illuminazione pubblica (EKZ) e data center (Equinix), con WinCC OA, TIA Portal, PCS 7 e OPC UA." },
    { category: "logistik", description: "Sviluppo software per impianti di smistamento di pacchi e invii misti, tra cui per DHL Express e la Posta svizzera." },
    { category: "abwasser", description: "Progetti di IDA, bacini di pioggia, recupero di calore dalle acque reflue e controlli di sicurezza in tutta la Svizzera." },
    { category: "stahl", description: "Messe in servizio internazionali di impianti siderurgici e industriali in Europa e in America." },
    { category: "retrofit", description: "Modernizzazione di impianti esistenti e migrazione di vecchi controllori (S5 → S7 → TIA) e da WinCC Advanced a WinCC Unified." },
    { category: "kies", description: "Visualizzazione di impianti per la ghiaia con WinCC Unified, tra cui Kieswerk Birr e KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Soluzioni bus e di comunicazione come il comando di illuminazione DALI dell'IDA Rorbas." },
  ],
  pt: [
    { category: "infrastruktur", description: "Infraestrutura crítica e energia: iluminação pública (EKZ) e centros de dados (Equinix), com WinCC OA, TIA Portal, PCS 7 e OPC UA." },
    { category: "logistik", description: "Desenvolvimento de software para instalações de triagem de encomendas e envios mistos, entre outros para a DHL Express e os Correios da Suíça." },
    { category: "abwasser", description: "Projetos de ETAR, bacias de tempestade, recuperação de calor de águas residuais e controlos de segurança em toda a Suíça." },
    { category: "stahl", description: "Colocações em serviço internacionais de instalações siderúrgicas e industriais na Europa e na América." },
    { category: "retrofit", description: "Modernização de instalações existentes e migração de controladores antigos (S5 → S7 → TIA) e de WinCC Advanced para WinCC Unified." },
    { category: "kies", description: "Visualização de instalações para instalações de cascalho com WinCC Unified, incluindo Kieswerk Birr e KIBAG Kies Schafisheim." },
    { category: "kommunikation", description: "Soluções de bus e comunicação como o controlo de iluminação DALI da ETAR Rorbas." },
  ],
};

export function getProjects(locale: string): Project[] {
  const t = txt[pageLocale(locale)];
  return base.map((b, i) => ({ ...b, ...t[i] }));
}
export function getCategoryLabels(locale: string): Record<ProjectCategory, string> {
  return categoryLabelsByLocale[pageLocale(locale)];
}
export function getReferenceHighlights(locale: string) {
  return highlightsByLocale[pageLocale(locale)];
}
